puddle/core/urls.py
from django.urls import path

from . import views
app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path ('contact/', views.contact, name= 'contact'),
]

puddle/item/urls.py
from django.urls import path

from . import views

app_name ='item'

urlpatterns=[
    path('<int:pk>/', views.detail, name='detail'),

]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/models.py
from django.db import models

# Create your models here.

puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name 

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model= User
        fields =('username','email','password1','password2')
        

puddle/core/views.py
from django.shortcuts import render

from item.models import Category,Item

from . forms import SignupForm

def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories' : categories,
        'items':items,
    })

def contact(request):
    return render (request, 'core/contact.html')

def signup(request):
    form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
        
    })

puddle/item/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:3]
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name "viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %} {% endblock %} | Puddle</title>
    </head>

    <body>
        <nav class ="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Puddle</a>

            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            </div>
        </nav>
        <div class="px-6 py-6">  
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
          <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum. </p>
          </div> 
          <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
             <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
             <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
             <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
             <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>

            </ul>

          </div>

        </footer>
    </body>
    </html>
    

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
<h1>The contact page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class= "mb-12 text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div>
            <a href ="{% url 'item:detail' item.id %}">
                <div>
                    <img src ="{{ item.image.url }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl"> {{ item.name }}</h2>
                    <p class="text-gray-500">Price: {{ item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class= "mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href ="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl"> {{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }} items </p>
                </div>
            </a>
                </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

puddle/core/templates/core/signup.html
 {% extends 'core/base.html' %}
 {% block title %} Sign up {% endblock%}
 {% block content%}

 <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
 </div>
 {% endblock %}

puddle/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.name}}</h1>
        <p class="text-gray-500"><strong>Price: </strong> {{item.price}}</p>
        <p class="text-gray-500"><strong>Seller: </strong> {{item.created_by.username}}</p>

        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong><br>
            {{item.description}}

        </p>
        {% endif %}
        <a hreaf="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
    </div>

</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class= "mb-12 text-2xl text-center">Related items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
        <div>
            <a href ="{% url 'item:detail' item.id %}">
                <div>
                    <img src ="{{ item.image.url }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl"> {{ item.name }}</h2>
                    <p class="text-gray-500">Price: {{ item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}